const words = [
  {
    question: "Push The Numbers To Make A Call",
    a: "Hold On",
    b: "Dial",
    c: "Call Back",
    d: "Hang Up",
    correct: "Dial",
  },
  {
    question: "Being Used",
    a: "Dial",
    b: "Get Cut Off",
    c: "Call Back",
    d: "Engaged",
    correct: "Engaged",
  },
  {
    question: "I Like Italian Food.<br />He Said He ______ Italian Food.",
    a: "Liked",
    b: "Had Liked",
    c: "Did Like",
    d: "Has Liked",
    correct: "Liked",
  },
  {
    question:
      "It Was Snowing This Morning.<br />She Told Me It _______ Snowing That Morning.",
    a: "Had Been",
    b: "Has Been",
    c: "Was",
    d: "Is Going To Be",
    correct: "Had Been",
  },
  {
    question: "Could You ____ The Phone?<br />I Think Its Important.",
    a: "Pick Up",
    b: "Dial",
    c: "Call Back",
    d: "Cut Off",
    correct: "Pick Up",
  },
  {
    question:
      "'By the time I'm 60 you'll have grown up' - my mum said <br />His mum said he ______ by the time she's 60",
    a: "Would have grown up",
    b: "Will grow up",
    c: "Was going to grow up",
    d: "would grow up",
    correct: "Would have grown up",
  },
  {
    question: "Ile miejsc zwiedza przed koncem lata?",
    a: "How many places are they going to visit by the end of summer",
    b: "How many places will have they visited ...",
    c: "How many places will they have been visiting ...",
    d: "How many places will they have visited ...",
    correct: "How many places will they have visited ...",
  },
  {
    question: "Krotko mowiac",
    a: "being direct",
    b: "to talk briefly",
    c: "to cut a long story short",
    d: "speaking shortly",
    correct: "to cut a long story short",
  },
  {
    question: "They ____ at midnight",
    a: "will be sleeping",
    b: "will sleep",
    c: "is be sleeping",
    d: "will been sleeping",
    correct: "will be sleeping",
  },
  {
    question: "____ a horse tomorrow",
    a: "she shall have been riding",
    b: "she'll riding",
    c: "she will be riding",
    d: "she would been riding",
    correct: "she will be riding",
  },
  {
    question: "_____ the whole evening",
    a: "She will be singing",
    b: "She is going singing",
    c: "She will have been singing",
    d: "She will been sing song",
    correct: "She will be singing",
  },
  {
    question: "'I like big burgers' - he said",
    a: "He said he likes big burgers",
    b: "He told me he liked big burgers",
    c: "He said he liked big burgers",
    d: "He said he's liked big burgers",
    correct: "He said he liked big burgers",
  },
  {
    question: "Have you visited London?______.",
    a: "Not yet",
    b: "Ever",
    c: "Already",
    d: "Not",
    correct: "Not yet",
  },
  {
    question: "The tree ______ by lightning.",
    a: "was flashed",
    b: "struck",
    c: "was struck",
    d: "flashed",
    correct: "was struck",
  },
  {
    question: "Can you tell me when ______ ?",
    a: "the train leaves",
    b: "does the train leave",
    c: "leaves the train",
    d: "does leave the train",
    correct: "the train leaves",
  },
];